### PR TITLE
no need to use array_push

### PR DESCRIPTION
**Pull request by pomaxa**
subj

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
@pomaxa Thanks for your suggestion. You right, in this case we could have avoided `array_push()` function. But I think it'll be better to improve this `push()` method and allow developers to push a few values at once like that provided by [array_push](http://php.net/manual/en/function.array-push.php) function.

What do you think?

**Comment by pomaxa** [comment]
@bocharsky-bw - I think it will be better to keep it simple, add keep it working the same way 
`public function unshift($element)` is working. At now it's accept only one element. 

It will be strange if push method will allow multiple elements, and unshift, - only one.

**Comment by bocharsky-bw** [comment]
Well, now we could simply use next syntax to add new elements to array:

``` php
$a = MutableArray::create(['a', 'b', 'c']);
$a[] = 'd'; // adding 'd' to array
// or do it with method call:
$a->offsetSet(null, 'e'); // equal to: $a[] = 'e';
```

Maybe we could improve `push` / `unshift` and implement a new feature which allows us to add / remove a multiple items at once with `push` / `unshift` accordingly. It also could be considered from performance point, you could check [this](http://stackoverflow.com/questions/559844/whats-better-to-use-in-php-array-value-or-array-pusharray-value) topic and my simple performance tests: [single argument](https://ideone.com/PXSfYG) and [multiple arguments](https://ideone.com/c2YmGH).

BTW, we could add a new `add()` method in order to more simple addition of single item than `offsetSet(null, /* new item */)` method if it need.

Is it sounds good?

**Comment by bocharsky-bw** [comment]
@pomaxa I just created alternative PR https://github.com/bocharsky-bw/Arrayzy/pull/11 with multiple arguments for `push`/`unshift`. What do you think?

**Comment by pomaxa** [comment]
@bocharsky-bw I think it looks much better.

**Comment by bocharsky-bw** [comment]
@pomaxa Anyway, thank you to point it! I'll be glad your further PRs!

**Comment by bocharsky-bw** [comment]
@pomaxa Maybe we should add an `add()` method to quickly add a new single value to array? I think it's a nice name for such array builder.

**Pull request closed without merging**
